name: Generate Binaries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: chmod +x .github/scripts/build.sh
    - name: Run a one-line script
      run: .github/scripts/build.sh
