name: Generate Binaries

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: download armhf toolchain
      run: wget https://releases.linaro.org/components/toolchain/binaries/7.5-2019.12/arm-linux-gnueabihf/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf.tar.xz
    - name: enable execution of script
      run: chmod +x .github/scripts/build.sh
    - name: Run build script
      run: .github/scripts/build.sh
